pingone:
  target-environment-id: 43af5a31-2a4c-49e5-8553-e8b5a39fb917
  region: Europe

  services:
    protect:
      risk-policies:
        names:
          - "PingOne Risk Policy"
          - "PingOne Risk Policy 2"
          - "PingOne Risk Policy 3"

    mfa:
      fido2-policies:
        names:
          - "PingOne FIDO2 Policy"
          - "PingOne FIDO2 Policy 2"
          - "PingOne FIDO2 Policy 3"

    platform:
      directory-schema:
        attribute-names: []